apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /guestbook        # Access at http://<ingress-ip>/guestbook
        pathType: Prefix
        backend:
          service:
            name: kustomize-guestbook-ui   # Kustomize adds "kustomize-" prefix
            port:
              number: 80